### ISSUE TITLE
Could you please provide the code for processing the data (and the data)?

### ISSUE THREAD

**Issue by LinjianLi** [lanse-sir/sup#2]
For instance:

- code for parsing sentences into syntactic trees and keep the top 3 layers
- code for building the vocab file
- code for training the syntactic seq2seq neural parser evaluator
- file `para1m_fine-tune.yaml`
- and so on......

I should be most grateful if the missing codes and files needed to run the model can be released.

**Comment by lanse-sir** [comment]
ok. I'll upload it again. I remember it's all in the _autocg_ directory, but I just found out that it's not there. I'm sorry.

**Comment by lanse-sir** [comment]
Hi, I have uploaded missing files.
