### ISSUE TITLE
The autocg directory misses the decoder subdirectory

### ISSUE THREAD

**Issue by ZooLulu** [lanse-sir/sup#3]
The **model.py** file under **autocg** executes `from autocg.decoder.rnn_decoder import RNNDecoder`， but there is not decoder directory

**Comment by ZooLulu** [comment]
And can you provide access to download quaro data, it seems we don't have access to download data directly from the given link

**Comment by lanse-sir** [comment]
Thank you for pointing out this issue. We have corrected the download permission of the dataset, you can try again.
For the first problem, we don't find this _model.py_ file. Our model python file is _model_cvae.py_, the _train_cvae.py_ and _fine_tune.py_ is training file.

**Comment by ZooLulu** [comment]
thanks~
