### ISSUE TITLE
How to process raw data to parse.txt and template.txt

### ISSUE THREAD

**Issue by ZooLulu** [lanse-sir/sup#4]
xxx_parse.txt and xxx_template.txt is required for train_cvae.py, so how to process a new dataset to get them.

**Comment by ZooLulu** [comment]
There are also files required for some parameters, such as **vocab**, **parser_vocab**, **word_occur**. How to generate them?

**Comment by lanse-sir** [comment]
you can use the autocg/build_vocab to get vocab、parser_vocab file.
